version: "3.6"

services:
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.1.2/meln5674-mongodb-community.zip;meln5674-mongodb-community,influxdb
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=meln5674-mongodb-community
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Airnominal
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_DATASOURCE_INFLUX_URL=${GF_DATASOURCE_INFLUX_URL}
      - GF_DATASOURCE_INFLUX_ORGANIZATION=${GF_DATASOURCE_INFLUX_ORGANIZATION}
      - GF_DATASOURCE_INFLUX_BUCKET=${GF_DATASOURCE_INFLUX_BUCKET}
      - GF_DATASOURCE_INFLUX_TOKEN=${GF_DATASOURCE_INFLUX_TOKEN}
      - GF_DATASOURCE_MONGO_URL=${GF_DATASOURCE_MONGO_URL}
      - GF_DATASOURCE_MONGO_DATABASE=${GF_DATASOURCE_MONGO_DATABASE}
      - GF_DATASOURCE_MONGO_USERNAME=${GF_DATASOURCE_MONGO_USERNAME}
      - GF_DATASOURCE_MONGO_PASSWORD=${GF_DATASOURCE_MONGO_PASSWORD}
    volumes:
      - grafanadata:/var/lib/grafana
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards:/etc/grafana/provisioning/dashboards

volumes:
  grafanadata:

networks:
  default:
    external: true
    name: airnominal
